name: blog-pr-preview

on:
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

#     - name: Install Ruby Dev                     
#       run: sudo apt-get install ruby-dev

#     - name: Install AsciiDoctor and Rouge
#       run: sudo gem install asciidoctor rouge

    - name: Setup base URL env var
      run: |
        export PRNUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") 
        echo BASEURL="https://rmoff-rmoff-blog-blog-pr-preview-'"$PRNUMBER"'.surge.sh/" >> $GITHUB_ENV

    - name: Report base URL env var
      run: echo "${{ env.baseurl }}" 

#     - name: Setup Hugo                           
#       uses: peaceiris/actions-hugo@v2
#       with:
#         hugo-version: '0.85.0'

#     - name: Build                                
#       run: hugo --buildFuture --buildDrafts --baseURL "${{ env.baseurl }}" 

#     - name: Deploy                               
#       uses: afc163/surge-preview@v1
#       id: preview_step
#       with:
#         surge_token: ${{ secrets.SURGE_TOKEN }}
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         dist: public
#         failOnError: 'true'
#         teardown: true
#         build: |
#           echo Deploying to surge.sh
